"""
Django settings for mental_health_backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

"""
Django settings for mental_health_backend project.
"""
"""
Django settings for mental_health_backend project.
Generated by 'django-admin startproject' using Django 6.0.2.
"""

from datetime import timedelta
from pathlib import Path
from celery.schedules import crontab
import os
import sys
from decouple import config   # pip install python-decouple
                               # python-decouple reads .env automatically — do NOT
                               # import or call load_dotenv() alongside it.

BASE_DIR = Path(__file__).resolve().parent.parent

# ─────────────────────────────────────────────────────────────────────────────
# SECRET_KEY  (SEC-01 / BE-01)
# ─────────────────────────────────────────────────────────────────────────────
# • Never hardcode. Set DJANGO_SECRET_KEY in your .env file.
# • python-decouple loads .env automatically — no load_dotenv() needed.
# • In CI set DJANGO_SECRET_KEY as a repo secret.
# • If the key is ever committed: rotate it and purge git history immediately.
# ─────────────────────────────────────────────────────────────────────────────
_is_ci = os.environ.get('CI') or 'test' in sys.argv or 'pytest' in sys.argv

SECRET_KEY = config(
    'DJANGO_SECRET_KEY',
    default='django-insecure-ci-only' if _is_ci else None,
)
if not SECRET_KEY:
    raise RuntimeError(
        "\n\nDJANGO_SECRET_KEY is not set.\n"
        "Generate one with:\n"
        "  python -c \"from django.core.management.utils import "
        "get_random_secret_key; print(get_random_secret_key())\"\n"
        "Then add it to your .env file (make sure .env is in .gitignore).\n"
    )

# ─────────────────────────────────────────────────────────────────────────────
# DEBUG  (SEC-02 / BE-03)
# ─────────────────────────────────────────────────────────────────────────────
# cast=bool means decouple converts 'True'/'False' strings correctly.
# Add  DJANGO_DEBUG=True  to your .env for local dev only.
# Never set True on a production server.
# ─────────────────────────────────────────────────────────────────────────────
DEBUG = config('DJANGO_DEBUG', default=False, cast=bool)

# ─────────────────────────────────────────────────────────────────────────────
# ALLOWED_HOSTS
# ─────────────────────────────────────────────────────────────────────────────
ALLOWED_HOSTS = config(
    'DJANGO_ALLOWED_HOSTS',
    default='localhost,127.0.0.1',
).split(',')

# ─────────────────────────────────────────────────────────────────────────────
# INSTALLED_APPS  (BE-02)
# ─────────────────────────────────────────────────────────────────────────────
# 'mood' scaffold app removed — it had zero migrations and caused
# OperationalError at startup.  All mood logic lives in mindset_api.
# ─────────────────────────────────────────────────────────────────────────────
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'mindset_api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mindset_api.middleware_debug_agent.DebugAgentExceptionMiddleware',
]

ROOT_URLCONF = 'mental_health_backend.urls'

TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [],
    'APP_DIRS': True,
    'OPTIONS': {'context_processors': [
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
    ]},
}]

WSGI_APPLICATION = 'mental_health_backend.wsgi.application'

# ─────────────────────────────────────────────────────────────────────────────
# DATABASE
# ─────────────────────────────────────────────────────────────────────────────
_db_engine = config('DB_ENGINE', default='django.db.backends.sqlite3')

if _db_engine == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': _db_engine,
            'NAME':     config('DB_NAME',     default='wellness_hub'),
            'USER':     config('DB_USER',     default='postgres'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST':     config('DB_HOST',     default='localhost'),
            'PORT':     config('DB_PORT',     default='5432'),
        }
    }

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE     = 'UTC'
USE_I18N      = True
USE_TZ        = True

STATIC_URL   = 'static/'
STATIC_ROOT  = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ─────────────────────────────────────────────────────────────────────────────
# CORS  (BE-03)
# ─────────────────────────────────────────────────────────────────────────────
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS   = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://localhost:3000',
).split(',')
CORS_ALLOW_CREDENTIALS = True

# ─────────────────────────────────────────────────────────────────────────────
# REST FRAMEWORK
# ─────────────────────────────────────────────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'EXCEPTION_HANDLER': 'mindset_api.exception_handlers.debug_aware_exception_handler',
}

# ─────────────────────────────────────────────────────────────────────────────
# JWT  (SEC-01 / BE-04 / BE-05)
# ─────────────────────────────────────────────────────────────────────────────
# JWT_SIGNING_KEY must be a DIFFERENT value from DJANGO_SECRET_KEY.
# Access token reduced to 60 min (was 1 day — far too long).
# ─────────────────────────────────────────────────────────────────────────────
_jwt_signing_key = config('JWT_SIGNING_KEY', default=SECRET_KEY if _is_ci else None)
if not _jwt_signing_key:
    raise RuntimeError(
        "\n\nJWT_SIGNING_KEY is not set.\n"
        "Generate one the same way as DJANGO_SECRET_KEY and add it to .env.\n"
    )

SIMPLE_JWT = {
    'SIGNING_KEY':           _jwt_signing_key,
    'ACCESS_TOKEN_LIFETIME':  timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# ─────────────────────────────────────────────────────────────────────────────
# CELERY
# ─────────────────────────────────────────────────────────────────────────────
CELERY_BROKER_URL     = config('CELERY_BROKER_URL',     default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_TIMEZONE       = TIME_ZONE

CELERY_BEAT_SCHEDULE = {
    'send-commitment-reminders': {
        'task':     'mindset_api.tasks.send_commitment_reminders',
        'schedule': crontab(minute=0),
    },
    'cleanup-old-commitments': {
        'task':     'mindset_api.tasks.cleanup_old_pending_commitments',
        'schedule': crontab(hour=3, minute=0),
    },
}

# ─────────────────────────────────────────────────────────────────────────────
# MEDIA
# ─────────────────────────────────────────────────────────────────────────────
MEDIA_URL  = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
os.makedirs(MEDIA_ROOT, exist_ok=True)

# ─────────────────────────────────────────────────────────────────────────────
# NOTE: Nothing below this line. Any SECRET_KEY / DEBUG assignment after this
# point would silently override the secure values above (was BE-01 bug).
# ─────────────────────────────────────────────────────────────────────────────