"""
Django settings for mental_health_backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

"""
Django settings for mental_health_backend project.
"""

from datetime import timedelta
from pathlib import Path
from celery.schedules import crontab
import os
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent


# ── BE-01 / S01: SECRET_KEY from env var — never hardcoded ───────────────────
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    import sys
    if 'test' in sys.argv or os.environ.get('CI'):
        SECRET_KEY = 'django-insecure-test-only-not-for-production'
    else:
        raise RuntimeError(
            "DJANGO_SECRET_KEY environment variable is not set.\n"
            "Generate one: python -c \"from django.core.management.utils import "
            "get_random_secret_key; print(get_random_secret_key())\""
        )

# ── BE-02 / S02: DEBUG from env var ──────────────────────────────────────────
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# ── BE-07: ALLOWED_HOSTS from env var ────────────────────────────────────────
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'mindset_api',
    # NOTE BE-06: add 'mood' here if the mood scaffold is intentional
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',   # BE-13: static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'mindset_api.middleware_debug_agent.DebugAgentExceptionMiddleware',
]

ROOT_URLCONF = 'mental_health_backend.urls'

TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [],
    'APP_DIRS': True,
    'OPTIONS': {'context_processors': [
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
    ]},
}]

WSGI_APPLICATION = 'mental_health_backend.wsgi.application'

# ── BE-12: SQLite for dev, PostgreSQL for production ─────────────────────────
_db_engine = os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3')
if _db_engine == 'django.db.backends.sqlite3':
    DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': BASE_DIR / 'db.sqlite3'}}
else:
    DATABASES = {'default': {
        'ENGINE': _db_engine,
        'NAME': os.environ.get('DB_NAME', 'wellness_hub'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'  # BE-13

# ── BE-03 / S03: CORS — only allow known origins ─────────────────────────────
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = os.environ.get(
    'CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://localhost:3000'
).split(',')
CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework_simplejwt.authentication.JWTAuthentication',),
    'EXCEPTION_HANDLER': 'mindset_api.exception_handlers.debug_aware_exception_handler',
}

# ── BE-04 / BE-05: Dedicated JWT key + 60-min access token ───────────────────
SIMPLE_JWT = {
    'SIGNING_KEY': os.environ.get('JWT_SIGNING_KEY', SECRET_KEY),
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),   # was 1 day — fix BE-05
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# ── BE-08 / Fix #12: Celery broker from env ───────────────────────────────────
# Add to requirements.txt:  redis==5.2.0  gunicorn==23.0.0  whitenoise  psycopg2-binary
# Start Redis locally:       docker run -d -p 6379:6379 redis:alpine
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_TIMEZONE = TIME_ZONE

CELERY_BEAT_SCHEDULE = {
    'send-commitment-reminders': {
        'task': 'mindset_api.tasks.send_commitment_reminders',
        'schedule': crontab(minute=0),
    },
    'cleanup-old-commitments': {
        'task': 'mindset_api.tasks.cleanup_old_pending_commitments',
        'schedule': crontab(hour=3, minute=0),
    },
}

load_dotenv()

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
os.makedirs(MEDIA_ROOT, exist_ok=True)
