# Generated by Django 6.0.2 on 2026-02-08 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindset_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='mood_value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
