# Generated by Django 5.2.3 on 2026-02-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindset_api', '0002_moodentry_sentiment_score_alter_moodentry_mood_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
