# Generated by Django 5.2.3 on 2026-02-10 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindset_api', '0005_alter_moodentry_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicStressEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Event name (e.g., 'Midterm Exams', 'Final Projects')", max_length=200)),
                ('start_date', models.DateField(help_text='Start date of the stress event')),
                ('end_date', models.DateField(help_text='End date of the stress event')),
                ('description', models.TextField(blank=True, help_text='Optional details about this event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Academic Stress Event',
                'verbose_name_plural': 'Academic Stress Events',
                'ordering': ['start_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='moodentry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Mood Entries'},
        ),
        migrations.AddField(
            model_name='moodentry',
            name='anxiety_level',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('extremely_severe', 'Extremely Severe')], help_text='Automatically categorized anxiety level', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='depression_level',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('extremely_severe', 'Extremely Severe')], help_text='Automatically categorized depression level', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='stress_level',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('extremely_severe', 'Extremely Severe')], help_text='Automatically categorized stress level', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='mood_value',
            field=models.IntegerField(help_text='Mood rating from 1 (Very Bad) to 5 (Very Good)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='note',
            field=models.TextField(blank=True, help_text='Optional text note from the student'),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='sentiment_score',
            field=models.FloatField(blank=True, help_text='Automatically calculated sentiment (-1 to 1) from the note', null=True),
        ),
    ]
