# Generated by Django 5.2.3 on 2026-02-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindset_api', '0006_academicstressevent_alter_moodentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text="Name of the academic event (e.g., 'Revision Week', 'Final Exams', 'Spring Break')", max_length=200)),
                ('start_date', models.DateField(help_text='Start date of the academic event')),
                ('end_date', models.DateField(help_text='End date of the academic event')),
                ('description', models.TextField(blank=True, help_text='Optional additional context about this event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Event',
                'verbose_name_plural': 'Academic Events',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='mindset_api_start_d_3a2c58_idx')],
            },
        ),
    ]
