# Generated by Django 5.2.3 on 2026-02-17 05:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindset_api', '0008_rename_created_at_to_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of sleep (e.g., night of Feb 10)')),
                ('hours_slept', models.FloatField(help_text='Hours of sleep (0-24)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(24.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Student tracking their sleep', on_delete=django.db.models.deletion.CASCADE, related_name='sleep_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sleep Log',
                'verbose_name_plural': 'Sleep Logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text="Subject or topic studied (e.g., 'Mathematics', 'Python Programming')", max_length=200)),
                ('start_time', models.DateTimeField(help_text='When the study session started')),
                ('end_time', models.DateTimeField(help_text='When the study session ended')),
                ('duration_minutes', models.IntegerField(editable=False, help_text='Auto-calculated duration in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Student logging the study session', on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Study Session',
                'verbose_name_plural': 'Study Sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.DeleteModel(
            name='AcademicStressEvent',
        ),
        migrations.AlterModelOptions(
            name='moodentry',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Mood Entry', 'verbose_name_plural': 'Mood Entries'},
        ),
        migrations.RemoveField(
            model_name='moodentry',
            name='mood_value',
        ),
        migrations.AlterField(
            model_name='academicevent',
            name='description',
            field=models.TextField(blank=True, help_text='Optional event description'),
        ),
        migrations.AlterField(
            model_name='academicevent',
            name='end_date',
            field=models.DateField(help_text='Event end date'),
        ),
        migrations.AlterField(
            model_name='academicevent',
            name='event_name',
            field=models.CharField(help_text="Name of the academic event (e.g., 'Final Exams', 'Project Deadline')", max_length=200),
        ),
        migrations.AlterField(
            model_name='academicevent',
            name='start_date',
            field=models.DateField(help_text='Event start date'),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='anxiety_level',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], help_text='AI-calculated anxiety level', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='depression_level',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], help_text='AI-calculated depression level', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='note',
            field=models.TextField(blank=True, help_text="Student's mood description (optional)"),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='sentiment_score',
            field=models.FloatField(blank=True, help_text='AI sentiment score (-1 to 1). Automatically calculated.', null=True),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='stress_level',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], help_text='AI-calculated stress level', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='When this mood was logged'),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='user',
            field=models.ForeignKey(help_text='Student who logged this mood', on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sleeplog',
            index=models.Index(fields=['user', 'date'], name='mindset_api_user_id_143fd7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sleeplog',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'start_time'], name='mindset_api_user_id_6afc25_idx'),
        ),
    ]
