# Generated by Django 5.2.3 on 2026-02-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindset_api', '0009_sleeplog_studysession_delete_academicstressevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Card headline shown in the carousel, e.g. 'Box Breathing'", max_length=200)),
                ('category', models.CharField(choices=[('Mood', 'Mood'), ('Focus', 'Focus'), ('Recovery', 'Recovery')], help_text='Wellness pillar this card belongs to', max_length=20)),
                ('image_url', models.URLField(blank=True, help_text='Thumbnail URL displayed on the card face')),
                ('content_link', models.URLField(help_text='URL or deep-link opened when the student taps the card')),
                ('color', models.CharField(default='#4A90D9', help_text="Hex background colour for the card, e.g. '#4A3728'", max_length=10)),
                ('action', models.CharField(default='open', help_text="Action token the frontend routes on: 'breathe', 'journal', 'sleep_tips', 'meditate', 'focus'", max_length=80)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated filter tags used by the recommendation engine, e.g. 'breathing,stress,anxiety'", max_length=300)),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Lower = shown earlier within its slot. Used as a tie-breaker when multiple cards match a rule.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive cards are never returned by the API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wellness Resource',
                'verbose_name_plural': 'Wellness Resources',
                'ordering': ['priority', 'category', 'title'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='mindset_api_categor_66aabf_idx')],
            },
        ),
    ]
