# Generated by Django 5.2.3 on 2026-03-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindset_api', '0010_wellnessresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='user_selected_mood',
            field=models.CharField(choices=[('SAD', 'Sad / Low'), ('ANX', 'Anxious'), ('STR', 'Stressed'), ('HAP', 'Happy'), ('NEU', 'Neutral')], default='NEU', help_text="Student's explicit mood choice: SAD, ANX, STR, HAP, or NEU", max_length=3),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='anxiety_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Low', help_text='Fused anxiety level — never empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='depression_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Low', help_text='Fused depression level — never empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='note',
            field=models.TextField(blank=True, help_text='Free-text mood description (optional)'),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='sentiment_score',
            field=models.FloatField(blank=True, help_text='Tuned sentiment score after keyword penalty (−1 to 1). Null only when no note AND no explicit mood provided.', null=True),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='stress_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Low', help_text='Fused stress level — never empty', max_length=20),
        ),
    ]
