# Generated by Django 5.2.3 on 2026-03-03 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindset_api', '0011_moodentry_user_selected_mood_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sleeplog',
            name='mindset_api_user_id_143fd7_idx',
        ),
        migrations.AddField(
            model_name='sleeplog',
            name='interruption_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times sleep was interrupted'),
        ),
        migrations.AddField(
            model_name='sleeplog',
            name='quality_tag',
            field=models.CharField(default='-', help_text='Good, Poor, or Not Bad', max_length=20),
        ),
        migrations.AddField(
            model_name='sleeplog',
            name='sleep_from',
            field=models.TimeField(blank=True, help_text='Time you went to bed', null=True),
        ),
        migrations.AddField(
            model_name='sleeplog',
            name='sleep_to',
            field=models.TimeField(blank=True, help_text='Time you woke up', null=True),
        ),
        migrations.AlterField(
            model_name='sleeplog',
            name='hours_slept',
            field=models.FloatField(default=0.0, help_text='Total hours (auto-calculated from From/To)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(24.0)]),
        ),
    ]
