# Generated by Django 5.2.3 on 2026-03-13 04:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindset_api', '0013_communitysnapshot_carepackage_crisischeckpoint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAffirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('self_worth', 'Self-Worth & Value'), ('capability', 'Capability & Strength'), ('belonging', 'Belonging & Connection'), ('growth', 'Growth & Learning'), ('uniqueness', 'Uniqueness & Authenticity'), ('resilience', 'Resilience & Courage'), ('compassion', 'Self-Compassion'), ('hope', 'Hope & Future')], max_length=20)),
                ('message', models.TextField(help_text='The affirmation message (warm, genuine, teen-appropriate)')),
                ('follow_up', models.TextField(blank=True, help_text='Optional follow-up reflection or question')),
                ('emoji', models.CharField(default='💖', max_length=10)),
                ('for_mood', models.CharField(blank=True, help_text='Show when user is feeling... (optional)', max_length=20)),
                ('times_shown', models.IntegerField(default=0)),
                ('times_saved', models.IntegerField(default=0)),
                ('times_shared', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', '-times_shown'],
            },
        ),
        migrations.CreateModel(
            name='DASEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('das_type', models.CharField(choices=[('depression', 'Depression'), ('anxiety', 'Anxiety'), ('stress', 'Stress')], max_length=20, unique=True)),
                ('simple_explanation', models.TextField(help_text='Simple, teen-friendly explanation of what this is')),
                ('why_it_happens', models.TextField(help_text='Why teens experience this (biological, social, environmental)')),
                ('common_experiences', models.JSONField(default=list, help_text='List of common feelings/experiences')),
                ('physical_signs', models.JSONField(default=list, help_text='Physical symptoms teens might notice')),
                ('emotional_signs', models.JSONField(default=list, help_text='Emotional/mental symptoms')),
                ('behavioral_signs', models.JSONField(default=list, help_text='Changes in behavior')),
                ('validation_message', models.TextField(help_text="Reassuring message that it's normal and okay")),
                ('helpful_strategies', models.JSONField(default=list, help_text='Evidence-based coping strategies')),
                ('when_to_get_help', models.TextField(help_text='Signs that professional help is needed')),
                ('common_myths', models.JSONField(default=list, help_text='List of myths and the truths')),
                ('emoji', models.CharField(default='💙', max_length=10)),
                ('color', models.CharField(default='#667eea', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DAS Education Content',
                'verbose_name_plural': 'DAS Education Content',
            },
        ),
        migrations.CreateModel(
            name='MoodBooster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('emoji', models.CharField(default='✨', max_length=10)),
                ('booster_type', models.CharField(choices=[('instant', 'Instant Relief (< 1 min)'), ('quick', 'Quick Pick-Me-Up (1-5 min)'), ('moderate', 'Mood Shift (5-15 min)'), ('deep', 'Deep Reset (15+ min)')], max_length=20)),
                ('mood_target', models.CharField(choices=[('sad', 'When feeling sad'), ('anxious', 'When feeling anxious'), ('stressed', 'When feeling stressed'), ('lonely', 'When feeling lonely'), ('angry', 'When feeling angry'), ('overwhelmed', 'When feeling overwhelmed'), ('tired', 'When feeling tired/drained'), ('bored', 'When feeling bored/empty')], max_length=20)),
                ('description', models.TextField(help_text='What this activity is')),
                ('instructions', models.TextField(help_text='Step-by-step instructions (teen-friendly)')),
                ('why_it_works', models.TextField(blank=True, help_text='Simple science behind why this helps')),
                ('difficulty_level', models.IntegerField(default=1, help_text='1=Super easy, 5=Takes effort', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('requires_privacy', models.BooleanField(default=False, help_text='Does this need a private space?')),
                ('requires_materials', models.BooleanField(default=False, help_text='Does this need any materials?')),
                ('materials_needed', models.TextField(blank=True, help_text='What materials if any')),
                ('times_tried', models.IntegerField(default=0)),
                ('times_helped', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-average_rating', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StressCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('academic', 'Academic Pressure'), ('social', 'Social Anxiety & Friendships'), ('romantic', 'Romantic Relationships'), ('family', 'Family Dynamics'), ('identity', 'Identity & Self-Image'), ('bullying', 'Bullying & Peer Pressure'), ('social_media', 'Social Media & FOMO'), ('future', 'Future & Career Uncertainty'), ('body_image', 'Body Image & Appearance'), ('loneliness', 'Loneliness & Isolation'), ('finances', 'Money Worries'), ('global_issues', 'World Events & Climate')], max_length=20, unique=True)),
                ('description', models.TextField(help_text='What this stress category means')),
                ('emoji', models.CharField(default='😟', max_length=10)),
                ('color', models.CharField(default='#FF6B6B', max_length=7)),
                ('why_it_happens', models.TextField(blank=True, help_text='Why teens experience this type of stress')),
                ('common_signs', models.JSONField(default=list, help_text='List of common signs/symptoms')),
                ('coping_strategies', models.JSONField(default=list, help_text='Healthy ways to cope with this stress')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Stress Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MoodBoosterUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tried_at', models.DateTimeField(auto_now_add=True)),
                ('mood_before', models.IntegerField(help_text='Mood before (1=worst, 10=best)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('mood_after', models.IntegerField(blank=True, help_text='Mood after (1=worst, 10=best)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('did_it_help', models.BooleanField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('booster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindset_api.moodbooster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tried_at'],
            },
        ),
        migrations.CreateModel(
            name='StressAssessmentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(auto_now_add=True)),
                ('responses', models.JSONField(help_text='Question ID to score mapping')),
                ('category_scores', models.JSONField(default=dict, help_text='Category type to percentage score mapping')),
                ('overall_stress_score', models.FloatField(default=0.0, help_text='Overall stress level (0-100)')),
                ('primary_stressor', models.CharField(blank=True, max_length=50)),
                ('secondary_stressor', models.CharField(blank=True, max_length=50)),
                ('found_helpful', models.BooleanField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='StressAssessmentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The question to ask (empathetic, teen-friendly language)')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('is_required', models.BooleanField(default=True)),
                ('weight', models.FloatField(default=1.0, help_text='How much this question impacts the stress score (0.5-2.0)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mindset_api.stresscategory')),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TeenMoodContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_trigger', models.CharField(blank=True, help_text='Main thing affecting mood today', max_length=50)),
                ('secondary_triggers', models.JSONField(default=list, help_text='Other contributing factors')),
                ('social_interaction_quality', models.IntegerField(blank=True, help_text='How were interactions today? (1=bad, 5=great)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('felt_supported', models.BooleanField(blank=True, help_text='Did you feel supported by someone today?', null=True)),
                ('felt_lonely', models.BooleanField(blank=True, help_text='Did you feel lonely today?', null=True)),
                ('screen_time_hours', models.FloatField(blank=True, help_text='Approximate screen time today', null=True)),
                ('social_media_mood_impact', models.CharField(blank=True, choices=[('positive', 'Made me feel better'), ('neutral', 'No real impact'), ('negative', 'Made me feel worse'), ('mixed', 'Both good and bad')], max_length=20)),
                ('ate_today', models.BooleanField(blank=True, help_text='Did you eat proper meals today?', null=True)),
                ('physical_activity', models.BooleanField(blank=True, help_text='Did you move/exercise today?', null=True)),
                ('tried_coping_strategy', models.BooleanField(default=False)),
                ('coping_strategy_used', models.TextField(blank=True)),
                ('coping_was_helpful', models.BooleanField(blank=True, null=True)),
                ('mood_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teen_context', to='mindset_api.moodentry')),
            ],
            options={
                'verbose_name': 'Teen Mood Context',
                'verbose_name_plural': 'Teen Mood Context',
            },
        ),
        migrations.CreateModel(
            name='SavedAffirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('why_it_resonated', models.TextField(blank=True, help_text='Why this message meant something')),
                ('times_revisited', models.IntegerField(default=0)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('affirmation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindset_api.dailyaffirmation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'affirmation')},
            },
        ),
    ]
