# Generated by Django 5.2.3 on 2026-03-13 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindset_api', '0014_dailyaffirmation_daseducation_moodbooster_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('hotline', 'Phone Hotline'), ('text', 'Text/SMS Service'), ('chat', 'Online Chat'), ('app', 'Mobile App'), ('website', 'Website Resource'), ('in_person', 'In-Person Location')], max_length=20)),
                ('severity_level', models.CharField(choices=[('immediate', 'Immediate Crisis (suicide, self-harm)'), ('urgent', 'Urgent Support Needed'), ('general', 'General Mental Health Support')], max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='For hotlines (e.g., 988, 1-800-273-8255)', max_length=50)),
                ('sms_number', models.CharField(blank=True, help_text='For text services (e.g., 741741)', max_length=50)),
                ('website_url', models.URLField(blank=True, help_text='For chat services or online resources')),
                ('short_description', models.TextField(help_text='Brief description shown in crisis modal')),
                ('detailed_info', models.TextField(blank=True, help_text='Full information about the resource')),
                ('hours_available', models.CharField(default='24/7', help_text='When this resource is available', max_length=100)),
                ('languages_supported', models.JSONField(default=list, help_text="List of languages (e.g., ['English', 'Spanish'])")),
                ('is_lgbtq_focused', models.BooleanField(default=False)),
                ('is_teen_focused', models.BooleanField(default=True)),
                ('is_campus_resource', models.BooleanField(default=False, help_text='Campus-specific resource')),
                ('campus_location', models.CharField(blank=True, help_text='Physical location on campus', max_length=200)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority resources shown first')),
                ('is_active', models.BooleanField(default=True)),
                ('times_shown', models.IntegerField(default=0)),
                ('times_clicked', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CrisisEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_type', models.CharField(choices=[('high_anxiety', 'Repeated High Anxiety'), ('severe_depression', 'Severe Depression Indicators'), ('self_harm', 'Self-Harm Mention'), ('suicidal_ideation', 'Suicidal Ideation Detected'), ('sleep_deprivation', 'Extreme Sleep Deprivation'), ('substance_use', 'Concerning Substance Use'), ('eating_disorder', 'Eating Disorder Indicators'), ('trauma_disclosure', 'Trauma Disclosure'), ('multiple_high_stress', 'Multiple High Stress Indicators'), ('manual_sos', 'User Clicked SOS Button')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low - Monitoring'), ('medium', 'Medium - Support Recommended'), ('high', 'High - Urgent Support'), ('critical', 'Critical - Immediate Intervention')], max_length=20)),
                ('detection_data', models.JSONField(help_text='What triggered the crisis detection (scores, keywords, etc.)')),
                ('user_viewed_resources', models.BooleanField(default=False)),
                ('resources_clicked', models.JSONField(default=list, help_text='Which resources user clicked on')),
                ('user_contacted_resource', models.BooleanField(default=False, help_text='User confirmed they contacted a resource')),
                ('user_dismissed', models.BooleanField(default=False, help_text='User dismissed the crisis alert')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_scheduled', models.BooleanField(default=False)),
                ('follow_up_completed', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('notifications_sent', models.JSONField(default=dict, help_text='What notifications were sent (push, email, SMS, admin)')),
                ('admin_reviewed', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_crises', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resources_displayed', models.ManyToManyField(blank=True, related_name='crisis_events', to='mindset_api.crisisresource')),
            ],
            options={
                'verbose_name': 'Crisis Event',
                'verbose_name_plural': 'Crisis Events',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SOSButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressed_at', models.DateTimeField(auto_now_add=True)),
                ('user_note', models.TextField(blank=True, help_text='Optional note from user about what they need')),
                ('current_mood', models.IntegerField(blank=True, help_text='Mood rating when SOS pressed (1-10)', null=True)),
                ('current_location', models.CharField(blank=True, help_text='User-provided location (optional)', max_length=200)),
                ('user_got_help', models.BooleanField(default=False, help_text='User confirmed they got help')),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('crisis_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mindset_api.crisisevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SOS Button Press',
                'verbose_name_plural': 'SOS Button Presses',
                'ordering': ['-pressed_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustedContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(help_text='e.g., Parent, Friend, Sibling, Counselor', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('notify_via_email', models.BooleanField(default=False)),
                ('notify_via_sms', models.BooleanField(default=False)),
                ('notify_on_severity', models.CharField(choices=[('medium', 'Medium and above'), ('high', 'High and above'), ('critical', 'Critical only')], default='critical', max_length=20)),
                ('user_confirmed_consent', models.BooleanField(default=False, help_text='User confirmed they have permission to add this contact')),
                ('contact_confirmed', models.BooleanField(default=False, help_text='Contact confirmed they want to receive alerts')),
                ('is_active', models.BooleanField(default=True)),
                ('times_notified', models.IntegerField(default=0)),
                ('last_notified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
