# Generated by Django 5.2.3 on 2026-03-14 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindset_api', '0016_privacyeducation_supportrecommendation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('gratitude', 'Gratitude'), ('reflection', 'Reflection'), ('goals', 'Goals & Aspirations'), ('challenges', 'Challenges'), ('self_care', 'Self-Care'), ('relationships', 'Relationships'), ('emotions', 'Emotions')], max_length=20)),
                ('prompt_text', models.TextField()),
                ('alternate_text_1', models.TextField(blank=True)),
                ('alternate_text_2', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy - Quick Reflection'), ('moderate', 'Moderate - Some Thought'), ('deep', 'Deep - Soul-Searching')], default='moderate', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='BuddyEncouragement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encouragements_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encouragements_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='CampusEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('finals', '📚 Finals Week'), ('midterms', '📝 Midterms'), ('registration', '🎓 Course Registration'), ('move_in', '🏠 Move-In Week'), ('graduation', '🎓 Graduation Week'), ('break_start', '✈️ Break Starts'), ('break_end', '🎒 Break Ends'), ('custom', '📅 Custom Event')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('typical_stress_level', models.CharField(choices=[('low', 'Low Stress'), ('moderate', 'Moderate Stress'), ('high', 'High Stress'), ('very_high', 'Very High Stress')], default='moderate', max_length=20)),
                ('is_campus_wide', models.BooleanField(default=True)),
                ('pre_event_support', models.TextField(blank=True, help_text="Support to offer BEFORE event (e.g., 'Create study plan')")),
                ('during_event_support', models.TextField(blank=True, help_text="Support DURING event (e.g., 'Extra check-ins')")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('academic', '📚 Academic Stress'), ('social', '👥 Social Anxiety'), ('relationships', '💕 Relationships'), ('family', '🏠 Family'), ('identity', '🔍 Identity'), ('loneliness', '😔 Loneliness'), ('body_image', '💭 Body Image'), ('general', '💬 General Support')], max_length=20)),
                ('content', models.TextField(help_text='Maximum 500 characters', max_length=500)),
                ('anonymous_id', models.CharField(help_text="Random ID shown as 'Student #1234'", max_length=20)),
                ('relate_count', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_count', models.IntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_ai_approved', models.BooleanField(default=False, help_text='AI moderation passed')),
                ('moderation_notes', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('campus_wide', models.BooleanField(default=True, help_text='Visible to entire campus vs just your cohort')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='CommunityPostingLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts_today', models.IntegerField(default=0)),
                ('last_post_date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityRelate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindset_api.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-related_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
                ('anonymous_id', models.CharField(max_length=20)),
                ('helpful_count', models.IntegerField(default=0)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('replied_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='mindset_api.communitypost')),
            ],
            options={
                'ordering': ['replied_at'],
            },
        ),
        migrations.CreateModel(
            name='AIContentModeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contains_crisis_language', models.BooleanField(default=False)),
                ('contains_identifying_info', models.BooleanField(default=False)),
                ('contains_bullying', models.BooleanField(default=False)),
                ('toxicity_score', models.FloatField(default=0.0, help_text='0.0 = clean, 1.0 = very toxic')),
                ('ai_approved', models.BooleanField(default=True)),
                ('flagged_for_review', models.BooleanField(default=False)),
                ('moderated_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mindset_api.communitypost')),
                ('reply', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mindset_api.communityreply')),
            ],
        ),
        migrations.CreateModel(
            name='CrisisContactPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('friend', '👋 Friend'), ('family', '🏠 Family Member'), ('partner', '💕 Partner'), ('counselor', '🎓 Campus Counselor'), ('hotline', '📞 Crisis Hotline')], max_length=20)),
                ('contact_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('default_message', models.TextField(default="Hey, I'm having a rough time right now. Can we talk?", help_text='Pre-written message (user can edit before sending)')),
                ('priority', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='EventSurvivalPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_breaks', models.TextField(blank=True, help_text='When/how to take breaks')),
                ('fun_activities', models.TextField(blank=True, help_text='One fun thing per day')),
                ('healthy_habits', models.TextField(blank=True, help_text='Sleep, meals, exercise goals')),
                ('support_people', models.TextField(blank=True, help_text='Who to reach out to')),
                ('breathing_reminders', models.BooleanField(default=True, help_text='Set breathing exercise reminders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindset_api.campusevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('prompted', 'Prompted Entry'), ('free_write', 'Free Write'), ('voice_note', 'Voice Note')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('voice_note_url', models.URLField(blank=True)),
                ('voice_note_duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('mood_tag', models.CharField(blank=True, choices=[('happy', '😊 Happy'), ('sad', '😔 Sad'), ('anxious', '😰 Anxious'), ('angry', '😠 Angry'), ('confused', '😕 Confused'), ('grateful', '🙏 Grateful'), ('hopeful', '✨ Hopeful'), ('overwhelmed', '🌊 Overwhelmed')], max_length=20)),
                ('written_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word_count', models.IntegerField(default=0)),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mindset_api.journalprompt')),
            ],
            options={
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-written_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalStreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('total_entries', models.IntegerField(default=0)),
                ('last_entry_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoodPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('anxious', '😰 Anxious'), ('sad', '😔 Sad'), ('angry', '😠 Angry'), ('stressed', '😫 Stressed'), ('happy', '😊 Happy'), ('energetic', '⚡ Energetic'), ('calm', '😌 Calm'), ('motivated', '💪 Motivated')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('spotify_url', models.URLField()),
                ('spotify_playlist_id', models.CharField(max_length=100)),
                ('apple_music_url', models.URLField(blank=True)),
                ('youtube_music_url', models.URLField(blank=True)),
                ('genre', models.CharField(blank=True, help_text='e.g., Lo-fi, Acoustic, Pop', max_length=50)),
                ('energy_level', models.CharField(choices=[('low', 'Low Energy'), ('medium', 'Medium Energy'), ('high', 'High Energy')], default='medium', max_length=20)),
                ('play_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['mood', '-play_count'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPersonality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality_type', models.CharField(choices=[('encouraging', '✨ Encouraging & Warm'), ('minimal', '💬 Minimal & Direct'), ('funny', '😄 Funny & Playful'), ('motivational', '💪 Motivational & Strong')], default='encouraging', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_personality', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('harmful', 'Harmful/Dangerous Content'), ('bullying', 'Bullying/Harassment'), ('identifying', 'Reveals Identifying Information'), ('spam', 'Spam/Off-topic'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mindset_api.communitypost')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mindset_api.communityreply')),
            ],
            options={
                'ordering': ['-flagged_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPlaylistHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_when_played', models.CharField(max_length=20)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('helped', models.BooleanField(blank=True, null=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindset_api.moodplaylist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_url', models.URLField(help_text='S3/Cloud Storage URL')),
                ('duration_seconds', models.IntegerField()),
                ('transcription', models.TextField(blank=True)),
                ('context', models.CharField(choices=[('journal', 'Journal Entry'), ('mood_note', 'Mood Note'), ('reflection', 'Reflection'), ('vent', 'Venting')], max_length=20)),
                ('mood_tag', models.CharField(blank=True, max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='WellnessBuddy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Connected'), ('declined', 'Declined'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('share_streak', models.BooleanField(default=True, help_text='Buddy can see your check-in streak')),
                ('share_mood_trend', models.BooleanField(default=True, help_text='Buddy can see if mood is improving/declining')),
                ('share_last_checkin', models.BooleanField(default=True, help_text='Buddy can see when you last checked in')),
                ('notify_on_checkin', models.BooleanField(default=False, help_text='Notify buddy when you check in')),
                ('notify_if_missed', models.BooleanField(default=True, help_text="Notify buddy if you haven't checked in for 3 days")),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('buddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_requests_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['-last_activity', 'is_approved'], name='mindset_api_last_ac_1bb9d6_idx'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['category', '-posted_at'], name='mindset_api_categor_151295_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communitypostinglimit',
            unique_together={('user', 'last_post_date')},
        ),
        migrations.AlterUniqueTogether(
            name='communityrelate',
            unique_together={('user', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='crisiscontactpriority',
            unique_together={('user', 'priority')},
        ),
        migrations.AlterUniqueTogether(
            name='eventsurvivalplan',
            unique_together={('user', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='wellnessbuddy',
            unique_together={('user', 'buddy')},
        ),
    ]
