# Generated by Django 6.0.3 on 2026-04-06 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindset_api', '0018_remove_voice_note_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='microcommitment',
            name='category',
            field=models.CharField(blank=True, choices=[('self_care', 'Self Care'), ('health', 'Health'), ('social', 'Social'), ('academic', 'Academic'), ('mindfulness', 'Mindfulness'), ('exercise', 'Exercise')], help_text='Category for custom commitments', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='microcommitment',
            name='commitment_text',
            field=models.CharField(blank=True, help_text='Custom commitment text entered by user', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='microcommitment',
            name='target_date',
            field=models.DateField(blank=True, help_text='Target date for completion', null=True),
        ),
        migrations.AlterField(
            model_name='microcommitment',
            name='commitment_type',
            field=models.CharField(blank=True, choices=[('breathing', '3 Deep Breaths'), ('water', 'Drink Water'), ('walk', 'Step Outside (2 min)'), ('friend', 'Text a Friend'), ('stretch', 'Quick Stretch'), ('gratitude', 'Write One Gratitude')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='microcommitment',
            name='mood_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='mindset_api.moodentry'),
        ),
    ]
