# Generated by Django 6.0.3 on 2026-04-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindset_api', '0019_microcommitment_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crisiscontactpriority',
            options={'ordering': ['priority'], 'verbose_name': 'Crisis Contact Priority', 'verbose_name_plural': 'Crisis Contact Priorities'},
        ),
        migrations.AlterModelOptions(
            name='notificationpersonality',
            options={'verbose_name': 'Notification Personality', 'verbose_name_plural': 'Notification Personalities'},
        ),
        migrations.AlterField(
            model_name='stressassessmentresponse',
            name='responses',
            field=models.JSONField(blank=True, help_text='Stored quiz answers from the student', null=True),
        ),
    ]
