# Generated by Django 6.0.3 on 2026-04-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindset_api', '0020_alter_crisiscontactpriority_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teenmoodcontext',
            name='secondary_triggers',
            field=models.CharField(default=list, help_text='Other contributing factors'),
        ),
    ]
