# Generated by Django 6.0.3 on 2026-04-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindset_api', '0021_alter_teenmoodcontext_secondary_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedmoodentry',
            name='original_id',
            field=models.IntegerField(blank=True, help_text='The ID of the mood entry before it was deleted', null=True),
        ),
    ]
