# Generated by Django 6.0.3 on 2026-04-19 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindset_api', '0022_alter_deletedmoodentry_original_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userplaylisthistory',
            options={'ordering': ['-played_at'], 'verbose_name': 'User playlist history', 'verbose_name_plural': 'User playlist histories'},
        ),
        migrations.AlterModelOptions(
            name='wellnessbuddy',
            options={'ordering': ['-requested_at'], 'verbose_name': 'Wellness buddy', 'verbose_name_plural': 'Wellness buddies'},
        ),
    ]
